### ISSUE TITLE
Top list displays 1h 79mins

### ISSUE THREAD

**Issue by jelmstrom** [perjansson/mcc#3]
Instead of 2h19 mins (or is it 1.79 hrs?)

**Comment by perjansson** [comment]
Yes, that's a feature. ;)

**Comment by perjansson** [comment]
Fixed it, the problem was in the backend (https://github.com/perjansson/mcc_backend_nodejs). Time was displayed as decimal number instead of being converted to time. Fix is deployed and available in production. #continuousDelivery :)

**Comment by jelmstrom** [comment]
#youRock
Den 20 feb 2014 19:02 skrev "Per Jansson" notifications@github.com:
